### ISSUE TITLE
Fatal error while component removal

### ISSUE THREAD

**Issue by marcosh** [zendframework/zend-component-installer#39]
As I was trying to remove `zend-form` from my expressive application with `Composer`, I got the following message:

```
Fatal error: Uncaught Error: Call to undefined method Zend\ComponentInstaller\Injector\ConfigInjectorChain::getConfigFile() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:617
Stack trace:
#0 /app/apps/public/vendor/zendframework/zend-component-installer/src/Collection.php(75): Zend\ComponentInstaller\ComponentInstaller_composer_tmp0->Zend\ComponentInstaller\{closure}(Object(Zend\ComponentInstaller\Injector\ConfigInjectorChain), 1)
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(620): Zend\ComponentInstaller\Collection->each(Object(Closure))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(597): Zend\ComponentInstaller\ComponentInstaller_composer_tmp0->removeModuleFromConfig('Zend\\Form\\Confi...', 'zendframework/z...', Object(Zend\ComponentInstaller\Collection))
#3 /app/apps/public/vendor/zendframework/zend-component-installer/src/Collection.php(75): Zend\ComponentInstaller\ComponentInstal in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 617
```

I guess this is caused by the call to `getConfigFile` present at line `617` of `ComponentInstaller::removeModuleFromConfig`, while that method is not present in `InjectorInterface`

**Comment by VIPrules** [comment]
The same issue. I try to remove my own package which is designed as a zend component and receive the following:

    Fatal error: Call to undefined method 
    Zend\ComponentInstaller\Injector\ConfigInjectorChain::getConfigFile() in 
    <my_project>\vendor\zendframework\zend-component-installer\src\ComponentInstaller.php on line 617`

I have to run composer twice so that it can to finish all its actions.
